### ISSUE TITLE
Compatibility issues OSC Mageplaza

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#312] opened 2019-10-25 12:04 UTC
Could you please get in contact with Mageplaza and fix your compatibility issues once and for all? Every update, either from you, or from them, breaks your cooperation with each other, leaving us with days of investigating and bug reporting. Either that, or fix #311   

My tests:
Magento 2.3.3, OSC 2.9.0, MyParcel 3.0.3 => myparcel not showing during checkout
Magento 2.3.3, OSC 2.9.0, MyParcel 3.0.4-beta2 => myparcel not showing during checkout
Magento 2.3.3, OSC 2.9.0, MyParcel 2.5.5 => myparcel radio buttons showing for delivery/pickup, but is working wrong/faulty

Magento 2.3.3, standard checkout, MyParcel 3.0.3 => myparcel not showing during checkout
Magento 2.3.3, standard checkout, MyParcel 3.0.4-beta2 => myparcel not showing during checkout
Magento 2.3.3, standard checkout, MyParcel 2.5.5 => myparcel not showing during checkout

Please let us know which working (!) version we should pick in combination with Magento 2.3.3.

Thanks!

**Comment by Calypso971** [comment] 2019-12-05 11:09
Can only agree with you. Had problems with the MyParcel extension (the famous #228 bug). Said to be fixed, wasn't. Again filed a bugreport, said to be fixed in 3.2.1 but in that version (in combination with Magento 2.3.3) the whole block is not displayed (just for a very short time and then it's gone again, so there is something going wrong in the creation order of the code). Worked in exactly the same setup with the version they first told that fixed the original bug, but after upgrading to MyParcel 3.2.1 this started to happen.

It's what we Dutchies call "Van de regen in de drup". Customer is angry because we are still not able to provide him with the functionality he expects, and when we point to the MyParcel Plugin developers his reaction only is "But MyParcel say they have a plugin".

**Comment by RichardPerdaan** [comment] 2019-12-05 12:06
Hi @Calypso971 and @Kroellie,

It is indeed true that there were problems with Magento 2.3.3 and MyParcel. These problems are fixed from version 3.1.1 of the MyParcel plugin.

The delivery options are visible with Magento 2.3.3 with the standard checkout:
![screencast2019-11-2815-27-18](https://user-images.githubusercontent.com/11389731/70233833-a2453d00-175f-11ea-9f40-0d40d8c74d4b.gif)
 
We are currently working on an adjustment of the delivery options so that the problem with the Mageplaza checkout will also be solved. This will be a major change for the MyParcel plugin and this version will not going live this year.

**Comment by Calypso971** [comment] 2019-12-05 12:37
@RichardPerdaan: As said in my post: I've installed the version that you have posted; it says in your post it's 3.1.2, it's downloaded as 3.1.2 and says it's 3.1.0 in the backend because you've forgotten to update the version in the configfile it reads that version from.

Is there a more recent version now that is strange enough one version number less? I suspect I'm having the latest version (i.e. 3.1.2) and that still has the problem as I mentioned.

**Comment by RichardPerdaan** [comment] 2019-12-05 13:09
Hi @Calypso971,

We have never released version 3.2.x.
Can you install 3.1.3 and save one more time the checkout settings?

I expect that there is a problem with the parent_method and that has been solved in version 3.1.3

**Comment by Calypso971** [comment] 2019-12-05 14:24
First of all: I had edited the mention of 3.2.x because I realised I made a mistake there in version numbers. I meant 3.1.2 (the one that reported itself as 3.1.0).

OK. 3.1.3 now..

![image](https://user-images.githubusercontent.com/15913397/70242620-6adf8c00-1771-11ea-8129-090a18747fd3.png)

OK, now the MyParcel block is back again. But bug #288 is still there...

My MyParcel block is "attached" to the tablerate block. Without entering postcode:

![image](https://user-images.githubusercontent.com/15913397/70243424-d83fec80-1772-11ea-8abc-14aceb7741a0.png)

Entered postcode:

![image](https://user-images.githubusercontent.com/15913397/70243485-ed1c8000-1772-11ea-82d3-036a741c65ee.png)

Clicked other method:

![image](https://user-images.githubusercontent.com/15913397/70243509-fd345f80-1772-11ea-84e7-243ca63b461d.png)

Oops... the original problem is still there...

Going back to a MyParcel method:

![image](https://user-images.githubusercontent.com/15913397/70243541-10dfc600-1773-11ea-8c67-9694dee7e8c9.png)

Then the other method is deselected.

**Comment by RichardPerdaan** [comment] 2020-08-05 14:03
I have done multiple tests with the versions below

- MyParcel plugin: 4.1.1
- MyParcel SDK: v5.2.0
- OSC Mageplaza: 2.9.0

After several tests, I have been unable to reproduce the above issues.
In addition, from version 4.0.0 the problem with changing the shipping methods has been solved.

**Closed by RichardPerdaan** 2020-08-05 14:03 UTC
Labels: compatibility
