### ISSUE TITLE
Hyva checkout compatibility?

### ISSUE THREAD

**Issue by allrude** [myparcelnl/magento#783] opened 2023-11-08 08:52 UTC
### What problem does this feature solve?

it makes the myparcel module compatible with the Hyvä Checkout for Magento 2

The is a duplicate from #764 by Aquive from  Jun 9 but no activity since then

### What should the solution look like?

it can be done by building a Hyvä Compatibility Module see: https://docs.hyva.io/hyva-themes/compatibility-modules/index.html

### Additional context

Almost all big Payment providers have already made there modules compatible, but the shipping providers ar a bit ... slow

**Comment by mountainit-general** [comment] 2023-11-28 10:24
We have a couple projects moving to Hyvä Checkout currently using MyParcel in their checkout. We'd also like to know if there are any plans, or if not if we should create compatibility ourselves.

**Comment by Steekvlam** [comment] 2024-01-26 09:41
Is there any update on this?

**Comment by wigman** [comment] 2024-01-26 14:20
+1 subscribing

If the MyParcel team needs any guidance in making this work with Hyvä, please reach out to me. Our core development team is here to help.

**Comment by EdieLemoine** [comment] 2024-01-26 14:23
Duplicate of #764

**Closed by EdieLemoine** 2024-01-26 14:23 UTC
Labels: feature

**Comment by wigman** [comment] 2024-01-26 14:26
@EdieLemoine we see high demand for MyParcel compatibility for our checkout. It would be great if we could get in contact to discuss it. Maybe you can follow up on #764 and provide a bit more context then just closing the issue without comment?

**Comment by wigman** [comment] 2024-01-26 14:49
Update: got confirmation that it is on their backlog. https://github.com/myparcelnl/magento/issues/764#issuecomment-1912174155
