### ISSUE TITLE
500 error when printing Label: createByCarrierName() must be of the type string, null given

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#509] opened 2020-11-09 19:39 UTC
**Describe the bug**
There's an error while trying to print a label for an order:
` 2020/11/09 20:30:02 [error] 1492#0: *880147 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to MyParcelNL\Sdk\src\Factory\ConsignmentFactory::createByCarrierName() must be of the type string, null given, called in /vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php on line 171 and defined in /vendor/myparcelnl/sdk/src/Factory/ConsignmentFactory.php:37
Stack trace:
#0 /vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php(171): MyParcelNL\Sdk\src\Factory\ConsignmentFactory::createByCarrierName(NULL)
#1 /vendor/myparcelnl/magento/Model/Sales/MagentoCollection.php(327): MyParcelNL\Magento\Model\Sales\TrackTraceHolder->convertDataFromMagentoToApi(Object(Magento\Sales\Model\Order\Shipment\Track), Array)
#2 /vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(171): MyParcelNL\Magento\Model" while reading response header from upstream, client: 86.88.84.171, server: boschruitenwissers.nl, request: "GET /admin2/myparcel/order/CreateAndPrintMyParcelTrack/key/123456/?selected_ids=23051&mypa_request_type=download&mypa_package_type=default&mypa_label_amount=1&mypa_paper_size=A4&mypa_positions%5B%5D=4 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm-nieuweruitenwissers.nl.sock:", host: "www.nieuweruitenwissers.nl", referrer: "https://www.nieuweruitenwissers.nl/admin2/sales/order/index/key/123456789/"
`

**To Reproduce**
1. Go to the order Grid
2. Click on Actions-Print MyPacel labels
3. See error

**Expected behavior**
The labels will be printed

**Screenshots**

**Desktop (please complete the following information):**
 - MyParcel Plugin version: 4.1.3
 - MyParcel SDK version: v5.2.2

**Comment by Mitchell-MyParcel** [comment] 2020-11-10 11:04
@gerben86 Duplicate of #487

**Closed by Mitchell-MyParcel** 2020-11-10 11:04 UTC

**Comment by gerben86** [comment] 2020-11-10 11:32
I don't think it's a duplicate, because the word "createByCarrierName()" isn't in the other thread.
The issue is that the orders are created with the old version of the plugin and the label is generated with the updated version of the plugin. This leads to errors...

**Comment by pierzakp** [comment] 2020-11-10 11:59
It seems that extension is not compatible with orders placed using older version of the extension.
Extension is introducing new column myparcel_delivery_options in sales_order table where in json format it's collecting additional information. New version of the extension expects information about carrier like: "carrier":"postnl". Adding such information manually into mentioned json for orders for which issue occurs solves the problem, but in general extension should handle it itself.
