### ISSUE TITLE
Uncaught TypeError: base64_encode() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by JKetelaar** [myparcelnl/magento#382] opened 2020-03-25 14:09 UTC
**Describe the bug**

**To Reproduce**
1. Connect with CLI to server
2. Use n98-magerun2
3. Run command `n98-magerun2 sys:cron:run myparcel_update_status`

```
Run MyParcelNL\Magento\Cron\UpdateStatus::execute PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, null given in /home/test/releases/MAGE2-GCW-release-178/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php:107
Stack trace:
#0 /home/test/releases/MAGE2-GCW-release-178/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php(107): base64_encode(NULL)
#1 /home/test/releases/MAGE2-GCW-release-178/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php(348): MyParcelNL\Sdk\src\Model\MyParcelRequest->setRequestParameters(NULL, NULL, 'Accept: applica...')
#2 /home/test/releases/MAGE2-GCW-release-178/vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(259): MyParcelNL\Sdk\src\Helper\MyParcelCollection->setLatestData()
#3 /home/test/releases/MAGE2-GCW-release-178/vendor/myparcelnl/magento/Cron/UpdateStatus.php(68): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->setLatestData()
#4 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/System/Cron/RunCommand.php(66): MyParcelNL\Magento\Cron\UpdateStatus->execute(Object(Magento\ in /home/test/releases/MAGE2-GCW-release-178/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php on line 107
```

**Expected behavior**
No error; cron ran

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Latest MyParcel

**Comment by RichardPerdaan** [comment] 2020-08-05 14:56
Hi @JKetelaar ,

Is this problem still present with version 4.1.1 of the MyParcel plugin?
It is not possible for me to recreate this problem with this version.

**Comment by RichardPerdaan** [comment] 2020-08-21 08:24
Hi @JKetelaar ,

If the problem is still present in the latest version of the plugin, please let me know.
For now I close the issue if it is not resolved, you can always reopen it

**Closed by RichardPerdaan** 2020-08-21 08:24 UTC
Labels: bug
